# Generated by Django 4.2 on 2023-04-25 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_attraction_alter_review_options_alter_review_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'ordering': ['name']},
        ),
    ]
