# Generated by Django 4.2 on 2023-04-25 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_attraction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={},
        ),
    ]
